require "assert.vv"

let i = false
try: i = true
catch _: assert(false, "exceptionless try body")
assert(i, "assigning from try body")

let i = false
try: do
  except 55
  assert(false, "except")
end catch e: i = e
assert(i == 55, "assigning from catch body")

try: 1 + "foo"
catch _: i = 12
assert(i = 12, "triggering builtin exception")
